#cargo-features = ["strip"]

[workspace]

members = ["tor", "utils", "logger", "tor-ffi"]

resolver = "2"

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
#strip = "symbols"
